-- AlterTable
ALTER TABLE `DemandeLogement` MODIFY `statut` ENUM('SOUMISE', 'EN_VALIDATION_DIRECTION', 'VALIDEE_DIRECTION', 'REJETEE_DIRECTION', 'EN_ETUDE_LOGEMENT', 'APPROUVEE', 'REJETEE', 'ANNULEE') NOT NULL DEFAULT 'SOUMISE';

-- AlterTable
ALTER TABLE `Mutation` MODIFY `statut` ENUM('SOUMISE', 'EN_VALIDATION_DIRECTION', 'VALIDEE_DIRECTION', 'REJETEE_DIRECTION', 'EN_ETUDE_LOGEMENT', 'APPROUVEE', 'REJETEE', 'ANNULEE') NOT NULL DEFAULT 'SOUMISE';
