-- AlterTable
ALTER TABLE `Logement` ADD COLUMN `piscine` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `jardin` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `sallesDeSport` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `groupeElectrogene` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `titreCommercial` VARCHAR(255) NULL;

-- AlterTable
ALTER TABLE `PhotoLogement` MODIFY `typePiece` ENUM('SALON', 'CHAMBRE', 'CHAMBRE_PRINCIPALE', 'CHAMBRE_2', 'CHAMBRE_3', 'CUISINE', 'SALLE_DE_BAIN', 'TOILETTES', 'BALCON', 'TERRASSE', 'JARDIN', 'GARAGE', 'ENTREE', 'FACADE', 'AUTRE', 'AUTRES_ESPACES') NOT NULL DEFAULT 'AUTRE';
